USE [master]
GO
/****** Object:  Database [HonestSign]    Script Date: 05.10.2021 8:30:06 ******/
CREATE DATABASE [HonestSign] ON  PRIMARY 
( NAME = N'HonestSign', FILENAME = N'E:\MSSQL.BI\DATA\HonestSign.mdf' , SIZE = 65536KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HonestSign_log', FILENAME = N'E:\MSSQL.BI\DATA\HonestSign_log.ldf' , SIZE = 11264KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [HonestSign] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HonestSign].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [HonestSign] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [HonestSign] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [HonestSign] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [HonestSign] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [HonestSign] SET ARITHABORT OFF 
GO
ALTER DATABASE [HonestSign] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [HonestSign] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [HonestSign] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [HonestSign] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [HonestSign] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [HonestSign] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [HonestSign] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [HonestSign] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [HonestSign] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [HonestSign] SET  DISABLE_BROKER 
GO
ALTER DATABASE [HonestSign] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [HonestSign] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [HonestSign] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [HonestSign] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [HonestSign] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [HonestSign] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [HonestSign] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [HonestSign] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [HonestSign] SET  MULTI_USER 
GO
ALTER DATABASE [HonestSign] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [HonestSign] SET DB_CHAINING OFF 
GO
EXEC sys.sp_db_vardecimal_storage_format N'HonestSign', N'ON'
GO
USE [HonestSign]
GO
/****** Object:  User [NT SERVICE\HealthService]    Script Date: 05.10.2021 8:30:06 ******/
CREATE USER [NT SERVICE\HealthService] FOR LOGIN [NT SERVICE\HealthService]
GO
/****** Object:  User [jirabot]    Script Date: 05.10.2021 8:30:06 ******/
CREATE USER [jirabot] FOR LOGIN [jirabot] WITH DEFAULT_SCHEMA=[dbo]
GO
sys.sp_addrolemember @rolename = N'db_owner', @membername = N'jirabot'
GO
/****** Object:  Table [dbo].[Settings]    Script Date: 05.10.2021 8:30:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Settings](
	[FNAME] [nvarchar](255) NOT NULL,
	[FVALUE] [nvarchar](max) NOT NULL,
	[FMODIFIEDON] [date] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [HonestSign] SET  READ_WRITE 
GO
